### ISSUE TITLE
ClientError? 

### ISSUE THREAD

**Issue by chocolocked** [IBM/image-recognition-and-information-extraction-from-image-documents#3]
When I ran 2.2 Connect to Object  Storage, I got this after trying to list buckets, can you help identify possible reasons? Thank you!

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-47-1c818a89a67a> in <module>()
----> 1 response = cos.list_buckets()
      2 buckets = [bucket['Name'] for bucket in response['Buckets']]
      3 print("Current Bucket List:")
      4 print(json.dumps(buckets, indent=2))
      5 print("---")

C:\ProgramData\Anaconda3\lib\site-packages\ibm_botocore\client.py in _api_call(self, *args, **kwargs)
    253                     "%s() only accepts keyword arguments." % py_operation_name)
    254             # The "self" in this scope is referring to the BaseClient.
--> 255             return self._make_api_call(operation_name, kwargs)
    256 
    257         _api_call.__name__ = str(py_operation_name)

C:\ProgramData\Anaconda3\lib\site-packages\ibm_botocore\client.py in _make_api_call(self, operation_name, api_params)
    543             error_code = parsed_response.get("Error", {}).get("Code")
    544             error_class = self.exceptions.from_code(error_code)
--> 545             raise error_class(parsed_response, operation_name)
    546         else:
    547             return parsed_response

ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied

**Comment by chocolocked** [comment]
Never mind I used the Admin credentials now it works.  I don't know how to close this. Sorry about the trouble!

**Comment by muralidharchavan** [comment]
No problem. I'll close this.
